In [1]:
import pandas as pd

path = '/home/eltito/repositorios/Curso-NumPy-Pandas-Matplotlib/Online_Retail.csv'
df = pd.read_csv(path, encoding='latin1')

In [10]:
country_count = df['Country'].value_counts()

# groupby = agrupame por 'Country', la sum() de 'Quantity'
country_group = df.groupby('Country')['Quantity'].sum()
country_group

Country
Australia                 83653
Austria                    4827
Bahrain                     260
Belgium                   23152
Brazil                      356
Canada                     2763
Channel Islands            9479
Cyprus                     6317
Czech Republic              592
Denmark                    8188
EIRE                     142637
European Community          497
Finland                   10666
France                   110480
Germany                  117448
Greece                     1556
Hong Kong                  4769
Iceland                    2458
Israel                     4353
Italy                      7999
Japan                     25218
Lebanon                     386
Lithuania                   652
Malta                       944
Netherlands              200128
Norway                    19247
Poland                     3653
Portugal                  16180
RSA                         352
Saudi Arabia                 75
Singapore                  5234
Spain                     26824
Sweden                    35637
Switzerland               30325
USA                        1034
United Arab Emirates        982
United Kingdom          4263829
Unspecified                3300
Name: Quantity, dtype: int64

In [18]:
country_stats = df.groupby('Country')['UnitPrice'].agg(MeanPrice = 'mean', SumPrice = 'sum')
country_stats

                       MeanPrice     SumPrice
Country
Australia               3.220612     4054.750
Austria                 4.243192     1701.520
Bahrain                 4.556316       86.570
Belgium                 3.644335     7540.130
Brazil                  4.456250      142.600
Canada                  6.030331      910.580
Channel Islands         4.932124     3738.550
Cyprus                  6.302363     3920.070
Czech Republic          2.938333       88.150
Denmark                 3.256941     1266.950
EIRE                    5.911077    48447.190
European Community      4.820492      294.050
Finland                 5.448705     3786.850
France                  5.028864    43031.990
Germany                 3.966930    37666.000
Greece                  4.885548      713.290
Hong Kong              42.505208    12241.500
Iceland                 2.644011      481.210
Israel                  3.633131     1079.040
Italy                   4.831121     3879.390
Japan                   2.276145      814.860
Lebanon                 5.387556      242.440
Lithuania               2.841143       99.440
Malta                   5.244173      666.010
Netherlands             2.738317     6492.550
Norway                  6.012026     6529.060
Poland                  4.170880     1422.270
Portugal                8.582976    13037.540
RSA                     4.277586      248.100
Saudi Arabia            2.411000       24.110
Singapore             109.645808    25108.890
Spain                   4.987544    12633.450
Sweden                  3.910887     1806.830
Switzerland             3.403442     6813.690
USA                     2.216426      644.980
United Arab Emirates    3.380735      229.890
United Kingdom          4.532422  2245715.474
Unspecified             2.699574     1204.010

In [21]:
country_stock_group = df.groupby(['Country', 'StockCode'])['Quantity'].agg(QuantitySum = 'sum')
country_stock_group

                       QuantitySum
Country     StockCode
Australia   15036              600
            15056BL              3
            16161P             400
            16169E              25
            20665                6
...                            ...
Unspecified 85180A               2
            85180B               1
            85212               12
            85213               12
            85227               10

[19839 rows x 1 columns]

In [25]:
def total_revenue(group):
    return (group['Quantity'] * group['UnitPrice']).sum()

revenue_per_country = df.groupby('Country').apply(total_revenue)
revenue_per_country

Country
Australia                137077.270
Austria                   10154.320
Bahrain                     548.400
Belgium                   40910.960
Brazil                     1143.600
Canada                     3666.380
Channel Islands           20086.290
Cyprus                    12946.290
Czech Republic              707.720
Denmark                   18768.140
EIRE                     263276.820
European Community         1291.750
Finland                   22326.740
France                   197403.900
Germany                  221698.210
Greece                     4710.520
Hong Kong                 10117.040
Iceland                    4310.000
Israel                     7907.820
Italy                     16890.510
Japan                     35340.620
Lebanon                    1693.880
Lithuania                  1661.060
Malta                      2505.470
Netherlands              284661.540
Norway                    35163.460
Poland                     7213.140
Portugal                  29367.020
RSA                        1002.310
Saudi Arabia                131.170
Singapore                  9120.390
Spain                     54774.580
Sweden                    36595.910
Switzerland               56385.350
USA                        1730.920
United Arab Emirates       1902.280
United Kingdom          8187806.364
Unspecified                4749.790
dtype: float64

In [49]:
country_rank_bests = revenue_per_country.sort_values(ascending=False)
top3_best = country_rank_bests.iloc[:3]

country_rank_worsts = revenue_per_country.sort_values()
top3_worst = country_rank_worsts.iloc[:3]

print(top3_best)
print()
print(top3_worst)

Country
United Kingdom    8187806.364
Netherlands        284661.540
EIRE               263276.820
dtype: float64

Country
Saudi Arabia      131.17
Bahrain           548.40
Czech Republic    707.72
dtype: float64